### ISSUE TITLE
Qusetion about evaluation superpoint about other features.

### ISSUE THREAD

**Issue by cumtchenchang** [rpautrat/SuperPoint#103]
Thank you for your good work, and I want to ask some questions about the feature and descriptor evaluation.
Q1:  When evaluating of the descriptors with homography estimation on HPatches, this code extract the feature and descriptor of SuperPoint, SIFT, and ORB. Is it fair to evaluate descriptors not using same features? 
Q2: When evaluating the repeatability on HPatches, you only use FAST, Harris, and Shi, may you add other features? such as ORB, SIFT, and SURF.
Q3: I find classical-detectors_shapes.yaml and detector_evaluation_magic_point.ipynb, how to use them. In addition, how to use your code to mean localization error, nearest neighbor mAP, and matching score.
Thank you, sincerely.

**Comment by rpautrat** [comment]
Q1: Homography estimation is indeed an evaluation of both the detector and descriptor, so it makes sense to compare it to the full SIFT or ORB. If you want an evaluation of the descriptors only, you can indeed do homography estimation with a fixed detector (e.g. SIFT detector) or compute the Nearest neighbor mean average precision as described in the original article.

Q2: It would be possible to add ORB, SIFT and SURF to the classical detectors (you just need to modify the file `classical_detectors.py`). The reason why I only compared to FAST, Harris and Shi is that I implemented the exact same baselines as in the original article.

Q3: yanhuanhuanyy already answered you how to reproduce `detector_evaluation_magic_point.ipynb` in https://github.com/rpautrat/SuperPoint/issues/102#issuecomment-525319637 (use `classical-detectors_shapes.yaml` to get the results on the classical detectors instead of `magic-point-shapes.yaml`). There is currently no implementation in this repo of the mean localization error, nn mAP and matching score.
