### ISSUE TITLE
homography matrix scale1 and scale2

### ISSUE THREAD

**Issue by heiko134470** [rpautrat/SuperPoint#126]
Hi rpautrat,

As we known, the homography matrix is updated through the following steps:
down_scale = np.diag(np.stack([1./scale1, 1./scale1, 1.]))
up_scale = np.diag(np.stack([scale1, scale1, 1.]))
real_H = up_scale @ homography @ down_scale @ translation

I was curious why up_scale is not np.diag(np.stack([1./scale2, 1./scale2, 1.]))?

scale1 is used to scale v_artisans1.ppm
scale2 is used to scale v_artisans5.ppm

**Comment by rpautrat** [comment]
Hi @heiko134470,

The names up_scale and down_scale are a bit misleading, because they are not necessarily increasing and decreasing the image size (depending on whether the scaling factor is greater or smaller than 1).

But if you look at the code, the current setup is the following:
https://github.com/rpautrat/SuperPoint/blob/bfb5bf5211d6d867f9c78160512d237e5ef7122c/superpoint/datasets/patches_dataset.py#L70-L73
And the homography is computed as
https://github.com/rpautrat/SuperPoint/blob/bfb5bf5211d6d867f9c78160512d237e5ef7122c/superpoint/datasets/patches_dataset.py#L91

If I read this last line from right to left (and I omit the translations), the new H takes the points with coordinates in the new resolution of image0, upscale brings those coordinates in the previous resolution of image0, the old H is applied, and down_scale brings the coordinates in the old resolution of warped_image0 to the new resolution of warped_image0.

So the two scales are correctly taken into account if I am not mistaken.

**Comment by heiko134470** [comment]
many thanks for your response, I got it.
