### ISSUE TITLE
Cannot reproduce perf with the provided pretrained model sp_v5.tgz

### ISSUE THREAD

**Issue by lostoy** [rpautrat/SuperPoint#137]
Hi,

I downloaded the pretrained model sp_v5.tgz from the other fork and write out script to dump descriptors and detections. Then I used the notebooks to evaluate repeatability and homography estimation, the performance is far worse than the ones in the notebook. Not sure what's wrong.

One thing that I notice is that the preprocessing of the sp_v5.tgz is different than this main repo. Here image is normalized by 1./255 while the saved_model is expecting 0-255 input.
Is there any other differences? Or can you share a newer model trained with this main repo?

**Comment by rpautrat** [comment]
Hi,

The pretrained model sp_v5.tgz was indeed an old version and there have been several changes since (including the normalization, but many others as well).

I should have done this a long time ago, but I finally removed the sp_v5.tgz and updated it with sp_v6.tgz, the most recent version. Let me know if you encounter any issue while using it.
