### ISSUE TITLE
Is there a need to match the keypoint to at most one warped keypoint before computing the repeatability ?

### ISSUE THREAD

**Issue by assiaben** [rpautrat/SuperPoint#14]
Hello,
First of all, thank you for providing this code, especially the metrics code.
I was going through the repeatability computations (https://github.com/rpautrat/SuperPoint/blob/master/superpoint/evaluations/detector_evaluation.py) and more specifically in compute_repeatability.
I see that you compute the euclidean distance between the keypoints and count every pair with an euclidean distance less that distance_thresh. This means that if one keypoint match several others, let's say N, you count N match. And I was wondering if there is a need to do a kind of matching to ensure that there is only at most one match per keypoint ?

I am not sure of this because I have a lot trouble finding an explicit definition of repeatability that specifies how to do the match and there are a lot of versions. For example here, they specify that they do a matching (https://github.com/vlfeat/vlbenchmarks/blob/master/%2Bbenchmarks/RepeatabilityBenchmark.m) but I never saw it specified in a paper or in other versions of code as here (http://www.robots.ox.ac.uk/~vgg/research/affine/). 

Thanks for your answer and if you know any resource that explicit the metrics definition (apart from Mikolajczyk papers), it would be help me a lot if you could share it please.

Thanks

**Comment by rpautrat** [comment]
To my knowledge, the first (and probably official) definition of repeatability dates from 2000 in _Evaluation of Interest Point Detectors_, by C. Schmid, R. Mohr and C. Bauckhage (https://hal.inria.fr/inria-00548302/file/Schmid-ijcv00.pdf, page 15). This definition suppose that there is a matching as you mention and is basically (nb of matches) / min(nb of points in image 1, nb of points in image 2).

However, here we implemented the repeatability metrics used by the original authors of SuperPoint, in order to compare with their results with the same metrics. This repeatability is defined by (Corr1 + Corr2) / (N1 + N2), where Ni is the number of points in image i and Corri the number of points in image i that have at least one match in the other image. So in this case we don't need to perform a matching, knowing that a point has at least a match is enough.

Note in particular the different denominator in the two definitions: the first (official?) one only considers the points in one image, whereas the second definition counts symmetrically the two images.

One could argue that the first definition is better as it counts only 1 for one point in image 1 matched with N points in image 2, but on the other hand with the second definition, the other points in image 1 will have a lower probability to have a match in image 2 (because already N points in image 2 are close to the same point). Thus the repeatability with the second definition would also be penalized.

So I guess it is up to you to choose the definition you want to use.

**Comment by assiaben** [comment]
Thank you for the details and for the paper link, I didn't know about that one. I think I will follow the SuperPoint definition as it is the most recent.

I have another question about the super point paper (http://openaccess.thecvf.com/content_cvpr_2018_workshops/papers/w9/DeTone_SuperPoint_Self-Supervised_Interest_CVPR_2018_paper.pdf)

One of their metrics on detectors are localization error and corner detection average precision which require ground truth 'corner location'. They gives the values of it in table 2 for the geometric shapes and table 4. It looks like table 4 contains metrics for HPatches but i didn't find ground truth 'corner' location in the Hpatch dataset. Would you know table 4 actually shows MLE on Hpatch or not ? And if yes, would you where the ground truth corner comes from ?

**Comment by rpautrat** [comment]
That's a good question, I have no idea. HPatches has no ground truth corners for sure (because you can't formally define a ground truth for corner points in a real image, there is always an ambiguity).

My guess is that they detected points on each image, for each scene they transformed the points of the images into the reference frame using the ground truth homography provided in the dataset and used the points of the reference image as ground truth. I don't see any other way (except use SIFT detections or another baseline as ground truth, but then you can't trust the ground truth).
