### ISSUE TITLE
Visualization of notebooks goes black

### ISSUE THREAD

**Issue by paalpri** [rpautrat/SuperPoint#141]
Hi! 

Again thanks so much for the repo, amazing stuff! 

I just wanted to give you a heads up that after the normalization updates, the visualization of some of the notebooks like synthetic shapes is black, because the draw keypoints function transform the image to uint8, which turns everything to zero.

I might have missed something when I implemented your changes, (since I'm not just pulling from your repo anymore but implementing them myself). If you turn your images back into (0, 255) range at some point let me know, then I missed that part. 

Also, I am having some weird results and I'm trying to compare a bit with your notebooks, but it seems they are not updated with the latest changes you have done (Correct me if I'm wrong here).
I would greatly appreciate it if you run them so the output gets updated If you have the time of course. 

Thanks! 
Paal

**Comment by rpautrat** [comment]
Hi!

Thanks for the comment, I should indeed update those notebooks with the last results and with the correction due to image normalization.

I'll probably not have the time in the next 2 weeks though, but we'll try to do it right after that.

**Comment by HZHZ66** [comment]
> Hi!
> 
> Again thanks so much for the repo, amazing stuff!
> 
> I just wanted to give you a heads up that after the normalization updates, the visualization of some of the notebooks like synthetic shapes is black, because the draw keypoints function transform the image to uint8, which turns everything to zero.
> 
> I might have missed something when I implemented your changes, (since I'm not just pulling from your repo anymore but implementing them myself). If you turn your images back into (0, 255) range at some point let me know, then I missed that part.
> 
> Also, I am having some weird results and I'm trying to compare a bit with your notebooks, but it seems they are not updated with the latest changes you have done (Correct me if I'm wrong here).
> I would greatly appreciate it if you run them so the output gets updated If you have the time of course.
> 
> Thanks!
> Paal



Hi.
In the fifth step of training, I generated the feature detection results of each algorithm as required. But when I ran Detector _ Repeatability _ Coco.ipynb. the visualization of the notebook  is black.
It's because the owner rpautrat  switched to normalized images between 0 and 1 and some notebooks have not been updated in the meantime and still assume images between 0 and 255. I just need to normalize correctly the images before visualizing them.  Could  you  please tell me how to  normalize correctly  the images? Thank  you  very  much!
![image](https://user-images.githubusercontent.com/62538300/83166713-e5e29780-a141-11ea-8b6f-b9a6d6f9411e.png)

**Comment by rpautrat** [comment]
The visualization of the images in black should have been fixed now. Closing this, unless you think it is not.
