### ISSUE TITLE
Question about detector loss and descriptor loss

### ISSUE THREAD

**Issue by 904281665** [rpautrat/SuperPoint#159]
Hi, Come back again ^.^
I still have some question about this paper. Regarding the descriptor loss part, although warped descriptor and descriptor are distinguished by cell distance, they have not completed the point coordinate matching. Is it correct to directly calculate the l2 distance of the two?
Looking forward to your answer, thank you very much^.^

**Comment by rpautrat** [comment]
Hi,
I am not sure to understand your question. The l2 distance between descriptor and warped_descriptor is already computed here. What do you mean by "directly calculate it"?
Point coordinate matching is defined by the cell distance: a point warped at a distance less than cell_dist of a point in the other image is considered as a match, and all other points are negative matches.

**Comment by 904281665** [comment]
Apologize for my bad english , I hope to express my problem through a flowchart.

![lADPD4Bhqs9RGB_NC9DND8A_4032_3024](https://user-images.githubusercontent.com/43224350/89022398-904e8500-d354-11ea-894c-678c88e605a3.jpg)
Based on the above proof, SuperPoint only has constraints on points whose offset is less than 8?

**Comment by rpautrat** [comment]
Beware that s is a multi-dimensional tensor, with 4 dimensions (h, w, h', w'). Here you draw only the cell [0, 0, :, :] of s for the top left corner cell. And in that case there is indeed only one positive constraint with the cell with offset less than 8. But for the other cell, we get a different s. For example the value of s[0, 1, :, :] is also [[1, 0], [0, 0]] and you have again one positive constraint and 3 negative ones.

So yes, in general you might miss some positive constraints or have too many of them because of this threshold at 8 pixels (depending on the homography), but on average you usually have a single positive constraint.

**Comment by 904281665** [comment]
You means the value of s[h,w,h',w'] is used to judge whether the distance between coord[h][w] and warped_coord[h'][w']  is less than 8?

**Comment by rpautrat** [comment]
Yes, exactly.

**Comment by 904281665** [comment]
！！got it ！！
Thank you so much！！

**Comment by 904281665** [comment]
problem solved
