### ISSUE TITLE
Ground Truth of Synthetic Ellipses

### ISSUE THREAD

**Issue by mfaisal59** [rpautrat/SuperPoint#16]
Hi,
In file synthetic_dataset.py line # 331 why the function is returning np.empty((0, 2), dtype=np.int), should it not return the centers of ellipses?

**Comment by rpautrat** [comment]
Hi,
The ground truth on geometrical shapes are any corners of the shape. As there is no corner in an ellipse, it has no ground truth. The ellipses are here a kind of "counter-example", a shape with no ground truth.
Note that we train here a corner detector, not a blob detector.

**Comment by mfaisal59** [comment]
But in the paper (section 4.1) authors have stated that the ground truths are Y-junctions, L-junctions, T-junctions as well as centers of tiny ellipses and end points of line segments.

![screenshot_1](https://user-images.githubusercontent.com/40632568/45081703-382f8980-b111-11e8-96dc-1ecd9e0b2137.jpg)

**Comment by rpautrat** [comment]
Indeed, but I think that by "tiny ellipses" they meant "almost points". Here we deal with large ellipses. But I concede that we have no such tiny ellipses in the current dataset.

However, when you look at the sample of synthetic shapes in the appendix, they have no small ellipses, but only big ellipses with no ground truth.
![ellipses](https://user-images.githubusercontent.com/32239569/45082268-3d80da00-b0f9-11e8-8466-9938c0f75e0f.png)

**Comment by mfaisal59** [comment]
Thanks for the clarification, I got the point.

**Comment by ddetone** [comment]
Hi, author of the SuperPoint paper here. I'd like to help clarify the confusion about the ellipses. Overall there were two ways we experimented with using them as ground truth.

One set of experiments was to create really narrow ellipses and treat the endpoints as ground truth, while leaving more circular shaped ellipses as negatives. These tended to help with repeatability, but only if you are really careful with the homographies apply on top of them. This is because when you apply more extreme homographies you can actually warp the narrow ellipses into circles and end up with inconsistent ground truth!

The other set of experiments we ran was to treat the centers of them as ground truth, and actually train a blob detector. This actually works! We trained a net on top of the blob ground truths but found it difficult at inference time to manage the scales of the network confidences across scales. More details can be found in Appendix Section B under "Blob Detection".

Hope this helps!

**Comment by rpautrat** [comment]
Thanks for the clarification @ddetone!
