### ISSUE TITLE
Pretrain model score

### ISSUE THREAD

**Issue by coper16** [rpautrat/SuperPoint#168]
Hi. 
I have a question.

On Nov,2019
This is your result(H-Patches -v)
<img width="724" alt="スクリーンショット 2020-09-09 18 28 43" src="https://user-images.githubusercontent.com/54351314/92582548-0affae00-f2cc-11ea-8c35-84a5e913c55d.png">

On Aug,2020
this is your result(H-Patches -v)
<img width="722" alt="スクリーンショット 2020-09-09 18 28 35" src="https://user-images.githubusercontent.com/54351314/92582576-10f58f00-f2cc-11ea-9756-539546c7c2ff.png">

So, why did pretrain model(by magicleap) score increase??

**Comment by rpautrat** [comment]
Hi,

That's indeed a good question!

The reason for that is that there was a bug (multiple ones actually, if I recall correctly) in the HPatches evaluation pipeline. It was pointed out in the issue https://github.com/rpautrat/SuperPoint/issues/117 and fixed in the commit eccbd5e0bfcec343ad2ae90ac7eca25e551b434f and the following ones.

Since it was a bug in the processing of the images and homographies, it impacted the evaluation of all methods at the same time. But the current results displayed in the ReadMe should be the right ones now.

**Comment by coper16** [comment]
Thanks, I saw issue #117 and understood.
