### ISSUE TITLE
Detector repeatability with pretrained superpoint model

### ISSUE THREAD

**Issue by anmakon** [rpautrat/SuperPoint#186]
Hi @rpautrat,

first of all thank you for your SuperPoint implementation and the continuous and hard work you seem to be putting into keeping this repository maintained and up to date! It really makes a big difference and I found your implementation to be easy to understand and adapt to my own research purposes.

I'm having some difficulties with reproducing your repeatability values for the pretrained superpoint model "sp_v6". The repeatability values under illumination changes seem to be somewhat close with ~0.5, but the ones with viewpoint changes drop to ~0.1. I've used the default configurations from superpoint_hpatches for exporting the detections with export_detections_repeatability.py (apart from setting nms to 4).

**Illumination changes:**
![HPatches_Repeatability_i](https://user-images.githubusercontent.com/58295383/103886555-99990600-50d9-11eb-8651-57ed57b2c104.png)

**Viewpoint changes:**
![HPatches_Repeatability_v](https://user-images.githubusercontent.com/58295383/103886445-6bb3c180-50d9-11eb-9d91-005fdf62f2d2.png)

Are the values in the ReadMe (Illumination 0.662; Viewpoint 0.674) the results that you got with the current sp_v6 model? If so, are there maybe any other parameters that I should consider changing? I've played around with resize, top_k, nms and the detection a bit, but couldn't get close to the values above.

**Comment by rpautrat** [comment]
Hi @anmakon,

The repeatability values displayed in the ReadMe are indeed coming from the current sp_v6 model. The parameters for the repeatability experiment on HPatches I used were normally the same as in the original SuperPoint paper: resize=[240, 320], nms=4, top_k=1000 (but keep_k_points=300 in the compute_repeatability function), and distance_thresh. If you have not tried with this combination, you can give it a try.

But 0.1 in viewpoint seems like too big of a difference to be just due to different evaluation parameters. The fact that it seems to work on illumination but not at all on viewpoint changes suggests that there might be something wrong with the homographies. Is there something that you could have modified related to the homographies maybe?

I have not modified this part of the pipeline in a long time, so I would expect it to be still working, but there is always a possibility that this is not compatible with this most recent version sp_v6...

**Comment by anmakon** [comment]
Hi @rpautrat ,

thanks for your fast response. I did indeed modified a few things related to the homographies, great catch. I'll check that right away and let you know if it changes things.

Thanks again!

**Comment by anmakon** [comment]
Hi @rpautrat ,

I did mix up some things when I modified some code in superpoint/datasets/patches_dataset.py. After fixing my self-introduced bug, I reach very similar values to what you got, 0.645 for viewpoint changes and 0.655 for illumination changes. I'll close this issue now, thanks again!
