### ISSUE TITLE
question about export detection

### ISSUE THREAD

**Issue by HardLaugh** [rpautrat/SuperPoint#187]
hello @rpautrat , thanks for your good jobs, i am a little confused about "export detection". In magicpoint or superpoint inference codes, I did not find anything about valid mask to mask out "crop and pad" , Am i right? sorry about my poor english and Looking forward to your answer

**Comment by rpautrat** [comment]
Hi,
The image resizing occurs in the dataloader, for example [here](https://github.com/rpautrat/SuperPoint/blob/6d830927e89308d353b5b368a76acb3405d5bada/superpoint/datasets/coco.py#L74). The image is first enlarged to be at least as big as the target size, while preserving the original ratio. Then it is cropped to get the target size. There is never a padding, only cropping. So when the image arrives in the model forward call, the image has already been cropped and without padding: there is no need for a valid mask since the entire image is valid.

**Comment by HardLaugh** [comment]
@rpautrat hi,
thanks for your reply, understand it 
i miss some points, i think it was like yolo ratio-preserving-resize previously
