### ISSUE TITLE
Generation patches max_angle

### ISSUE THREAD

**Issue by alexlorenzo** [rpautrat/SuperPoint#200]
Hello,

I have question regarging patches created.

Indeed when using the config `superpoint_coco.yaml `, the warped pairs are defined with a `max_angle: 1.57`

However, in the config `coco_patches_generation.yaml` the `max_angle` is defined as `3.14`.

Is it a reason why we change those parameters?

Thank you.

**Comment by rpautrat** [comment]
Hi,
The reason is that initially all `max_angle` were at 3.14, but we found out that we could reach better performance with 1.57 (at the cost of a smaller invariance to rotations). We didn't update the config `coco_patches_generation.yaml` since then, but feel free to change the `max_angle` to 1.57 as well. This would make more sense to train and test with the same parameters.

**Comment by alexlorenzo** [comment]
Thanks for your quick answer;
I will keep same parameters for train and test. 
I'm closing this issue.
