### ISSUE TITLE
superpoint error

### ISSUE THREAD

**Issue by jnanikarri7** [rpautrat/SuperPoint#206]
from superpoint.settings import EXPER_PATH
ImportError: No module named 'superpoint'
I am getting this error after running the detector_evaluation_magic_point.

**Comment by rpautrat** [comment]
Hi, did you follow the instructions of the Readme and installed the package with `make install`?

**Comment by jnanikarri7** [comment]
I did follow the instructions for the requirements and I wanted to only run the magic point visualizations using the pretrained data sets:
I think  detector_evaluation_magic_point file can get me the visualizations with $EXPER_PATH folder having the Magicpoint(synthetic) pretrained dataset.
Is there any pre-requisite that I should be doing to run this code?
Thank you!

**Comment by rpautrat** [comment]
So the line `pip3 install -e .` of the make install ran without error? If so, the package 'superpoint' should be properly installed on your system. Check that you don't have a mismatch with your Python environment and that you are using the same when running the install and when running the notebook. You might want to run instead `pip install -e .` if your pip3 is not already the same version as your pip.

Otherwise than that, $EXPER_PATH should point to the **parent folder** of the Magicpoint(synthetic) pretrained dataset.

If you run the  detector_evaluation_magic_point notebook from scratch, this won't work as it uses experiments previously computed. These experiments were previously computed from the script [export_detections.py](https://github.com/rpautrat/SuperPoint/blob/master/superpoint/export_detections.py).

**Comment by jnanikarri7** [comment]
ok, how can i get only the magic point visualizations output without actually running the entire code using pre-trained dataset?

**Comment by rpautrat** [comment]
You could run the script `match_features_demo.py` (instructions on how to use it are in the Readme) to visualize both the detections and matches produced by the network. If you don't want to see the matches, you can also comment the lines displaying the matches in the script.

**Comment by jnanikarri7** [comment]
I tried but getting not found in the archive error:
![e1](https://user-images.githubusercontent.com/77305979/117340551-41db9300-ae5e-11eb-8a47-6ef27b2dc3f2.PNG)

**Comment by jnanikarri7** [comment]
ok, now i extracted (without using the mentioned command) the pretrained weights sp_v6 and pasted them under $EXPER_PATH/saved_models/
now I ran match_features_demo.py using the second mentioned command(python match_features_demo.py sp_v6 $DATA_PATH/HPatches/i_pool/1.ppm $DATA_PATH/i_pool/6.ppm). It is now throwing up OSerror
![e2](https://user-images.githubusercontent.com/77305979/117369434-24202500-ae82-11eb-991b-a191f9faadd2.PNG)

**Comment by rpautrat** [comment]
Did you properly setup the EXPER_PATH? What do you get if you run `echo $EXPER_PATH` in a terminal? I think that the first command failed because your EXPER_PATH was not properly set.

Regarding the second try, this couldn't work : the saved_model sp_v6 provided in `pretrained_models` is different from the pretrained weights link given in the Readme. The first one is the exported graph of the network, while the second one is directly the output of a training. `match_features_demo.py` is only meant to be used with the first one, so it won't work with the second one. So you should rather fix the error of the previous command to untar the saved model.

**Comment by jnanikarri7** [comment]
I am not sure where its going wrong, I did make install and had given absolute paths for $exper_dir and $data_dir
and tried to untar still getting the same error:
![fri2](https://user-images.githubusercontent.com/77305979/117464497-f2ed3680-af0d-11eb-96f3-1dc5b43130a4.PNG)

**Comment by rpautrat** [comment]
It seems that you named the actual experiment folder '$EXPER_PATH' and '$DATA_DIR' for the data. This is probably not a good idea as it will mess up with the environment variables. You can choose any name for your folder storing experiments and data, for example `/home/smart1/Desktop/SuperPoint-master/experiments` and `/home/smart1/Desktop/SuperPoint-master/datasets`.

Then running make install will make sure that the _variables_ $EXP_PATH and $DATA_PATH are pointing to these two folders.

**Comment by jnanikarri7** [comment]
I did give the path but it's still not reflecting :
![f3](https://user-images.githubusercontent.com/77305979/117469644-34341500-af13-11eb-8dcd-c25f21f8e4d1.PNG)
![f4](https://user-images.githubusercontent.com/77305979/117469657-39915f80-af13-11eb-9e1f-7fa4214119d3.PNG)
the directory datasets and experiments shd be reflected in setup.sh file right?

**Comment by rpautrat** [comment]
Did you create the folder `experiments/saved_models`? It might just be that it is missing...

This command is anyway just to untar a file, you can achieve that in many ways and you don't have to stick to this command. Worst case, you just right click on it and select "Extract to"...

**Comment by jnanikarri7** [comment]
okay here is step wise procedure i followed skipping the extracting command:
1. created folders datasets, experiments
2. in datasets loaded HPatches and COCO training datasets
3. in experiments directory created subs saved_models and extracted the sp_v6 file to this
now it looks like this:
![sat1](https://user-images.githubusercontent.com/77305979/117544801-3c0dbb00-afe0-11eb-92b6-d31ed7f2a109.PNG)
I tried to execute the second command, running the demo file: (python match_features_demo.py sp_v6 $DATA_PATH/HPatches/i_pool/1.ppm $DATA_PATH/i_pool/6.ppm)
![sat](https://user-images.githubusercontent.com/77305979/117544817-59428980-afe0-11eb-989b-56d7a60928ef.PNG)

**Comment by rpautrat** [comment]
The folders architecture should be fine like this.

I think that the issue comes from your EXPER_PATH. For some reason, it is set to an empty string when you run `match_features_demo.py` (you can print it during the execution of the code to verify this). Or at least that's what I think, because the error says that it is looking for the path 'saved_models/sp_v6/saved_model.pb', instead of '/home/smart1/Desktop/SuperPoint-master/experiments/saved_models/sp_v6/saved_model.pb'. So you can hardcode the EXPER_PATH in the script, but I recommend you rather to find out why your EXPER_PATH doesn't have the proper value.

**Comment by jnanikarri7** [comment]
but I see my EXPER_PATH is pointing to the experiments directory in the code as well:
![sat3](https://user-images.githubusercontent.com/77305979/117545983-64e47f00-afe5-11eb-9b28-00d836b375af.PNG)
here should I need to give path for saved_model.pb instead of just giving experiments?

**Comment by rpautrat** [comment]
No, it should point to the experiment folder as it is now. This is really strange.

Can you try to hardcode the weights_dir with the right value '/home/smart1/Desktop/SuperPoint-master/experiments/saved_models/sp_v6' in [this line](https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/match_features_demo.py#L109)?

**Comment by jnanikarri7** [comment]
Thanks to you, I think the path issue was resolved with hardcode specified, now I ran the dem file instead now getting cv2.error:
![sun](https://user-images.githubusercontent.com/77305979/117578189-66c44600-b0aa-11eb-9155-85226c36f470.PNG)

**Comment by rpautrat** [comment]
I think this means that the image you read is empty, so you should probably double-check the path to the image you are using.

**Comment by rpautrat** [comment]
Hi, did you find the origin of your error?

**Comment by jnanikarri7** [comment]
Hey, thanks for getting back. I did find out the error but I couldn't resolve that why the dataset path is taken to be null, I'm still figuring out what could be the reason.

**Comment by rpautrat** [comment]
I see, then in case you find the solution and think that it might help others, don't hesitate to post your fix here.

**Comment by jnanikarri7** [comment]
yes, for surely will post if I found the fix

**Comment by akshadshyam** [comment]
Got the same error. Just confirm the path to the input images is correct.

**Comment by rpautrat** [comment]
Is the path absolute? It should start from the root / and not from your local home folder ~.

**Comment by akshadshyam** [comment]
Yes the path is absolute.

**Comment by rpautrat** [comment]
Well, this error can only come from a wrong path I think. You can try to run these simple lines and see if you get a None or not:
```
import cv2
img = cv2.imread(<your path>)
print(img)
```
If the output is None, your path is indeed wrong.
