### ISSUE TITLE
Question about the normalize step in descriptor loss calculation

### ISSUE THREAD

**Issue by Dai-z** [rpautrat/SuperPoint#211]
Hi Rémi,
Thanks for your works.
I’m reading your code and found something that confused me. It’s the code about descriptor loss calculation at `superpoint/models/utils.py:111. `.
![image](https://user-images.githubusercontent.com/24568699/118755511-9427a580-b89b-11eb-947e-2d196195b998.png)
Here you normalize the dot product result along two dimensions(I mean the flatten descriptors map) separately if I understood it correctly. I wonder that what is the difference compared with directly normalizing it at the whole 2D dimension?
Hope for your reply, thanks!

**Comment by rpautrat** [comment]
Hi @Dai-z,
I think you could normalize it directly at the whole 2D dimension and to reach a similar goal (disambiguating descriptors that are very close in the dot product), but doing the double normalization as it is done currently should yield more fine-grained results per descriptor.

In other words, if you do the normalization in a single step, you get the same normalization for all descriptors, and it will be based on the overall distributions of descriptors in the image. Whereas with the double normalization, each descriptor of one image has a different normalization than the other descriptors, and thus the normalization can be better fitted to this particular descriptor.

I hope this is clear... Since adding a second normalization is not very costly anyway and is more fine-grained, I went for this option. But you could probably try the single normalization and get similar results.

**Comment by Dai-z** [comment]
Got it. Thank you very much!
