### ISSUE TITLE
Erratic behavior while matching

### ISSUE THREAD

**Issue by Arka161** [rpautrat/SuperPoint#212]
I am not sure if there is a bug with the pre-processing module or the feature extraction for SuperPoint, I get strange results which are order of magnitudes worse than OpenCV's native ORB or SURF implementations. To give an example, a Harry Potter matching example looks like this: 

![image](https://user-images.githubusercontent.com/20723780/119193046-0ab8d480-ba4f-11eb-9e94-8736650b6cd9.png)

The SIFT module's results in the code seem to be much worse than using vanilla SIFT in OpenCV too, I am not sure how/why the resize engine causes these issues. To give an example, in native OpenCV, matches look something like this : 

![image](https://user-images.githubusercontent.com/20723780/119193179-3dfb6380-ba4f-11eb-8cc6-a5f7ac02a4ce.png)

According to the authors of the original SuperPoint paper, there definitely should be an improvement. I have ran the code as is by following the instructions in `README.md`, and I would inquire why the results are erratic. To confirm, I have tried other images too to confirm it's not dataset specific. Any guidance on why this happens could be helpful. My Conda environment is tailored to the same `requirements `mentioned in the file, and I am on a Windows computer. 

Could it be something with the pre-trained CNN bugging out?

**Comment by rpautrat** [comment]
Hi, the example you show is wrong indeed, there should be a bug in your pipeline somewhere. The keypoints are random and do not even cover the full image. What did you do exactly to get these matches?

You should pay extra attention if you resize the images and check the convention of the coordinates for the keypoints. In this repo, we mainly use the convention (rows, cols) instead of the (x, y) often used in OpenCV for example.

**Comment by Arka161** [comment]
Thank you for the comment. It definitely felt very random as you said! 
I have not added any extra resize parameters. I am using the default one for both of my images, I think it's 640 width and 480 height. 

The model is the default pre-trained model that you have linked in the superpoint folder. 
I manually hardcoded the dims to make sure I'm not wrong: 

`img_size = (640, 480)`

Do you have any other ideas why it would be buggy? Thank you

**Comment by rpautrat** [comment]
Ah then, this might be the issue. The image size should be reversed and should be `img_size = (480, 640)`. We are using the (rows, cols) convention everywhere in this repo, unlike OpenCV which is using the opposite. This would also explain why you don't get detection at the bottom of the image.

**Comment by Arka161** [comment]
![image](https://user-images.githubusercontent.com/20723780/119562023-dfe2bf00-bd73-11eb-96d8-5bdb459d0d0a.png)
Thank you for your reply. I tried the setting above. It still seems very wrong.

Furthermore, I have tried other random images, and the matching does not seem to work correctly. I know it is probably not a fault with the repo and I may be screwing up the resize, but I appreciate any help.

**Comment by rpautrat** [comment]
Are you using the script `match_features_demo.py`? Actually I checked and you were using the right convention with your `img_size = (640, 480)`. But the images you are showing are not resized to the same size (unless the image on the right has naturally a black side?), so there is definitely something going wrong in your resize.

**Comment by Arka161** [comment]
I did some investigation, and it looks like the black patch is just a front-end thing. OpenCV and other libraries automatically add it if the template image and the target image have different shapes. 

For example, I get this in my own vanilla OpenCV script: 
![image](https://user-images.githubusercontent.com/20723780/119692072-1a526780-be19-11eb-9b14-b675f62e3a32.png)

The re-size does not seem to be the issue. If I may request, could you give me sample images that worked properly for this script? 
I would try it out on my end. 

I would be happy to share the images I am using for this usecase too: 

Base: https://imgur.com/IrWPqn0
Bookshelf: https://imgur.com/87rrdnJ

I would be curious to see if there is any issue with the script somewhere, or if there is something trivial I am missing. 

Once again, I am grateful for the replies and help.

**Comment by rpautrat** [comment]
The problem with the black side is that it should not appear at all if you are resizing both images to the same size. And the fact that your keypoints seem to be correct, but displaced by some offset, makes me think that it is a resizing issue, but this could also be something else.

I ran SuperPoint on your images and got the following results:
With default resize: 
![sp_matches](https://user-images.githubusercontent.com/32239569/119697635-b0ee4b00-be50-11eb-8a87-d817830cbd7b.png)
Without resize: 
![sp_matches_no_resize](https://user-images.githubusercontent.com/32239569/119697658-b8adef80-be50-11eb-8204-ff187a801c3d.png)

You can see that the detected keypoints are well-localized on the corners of the image and are not random anymore, so this seems to be working correctly. The matching completely fails though, probably because the scale change is quite huge between the two images. SuperPoint is by construction a bit invariant to scale changes, but only up to a certain point, and it is not designed to succeed in the presence of such changes.

If you want to test it on images that work, you can use the HPatches images used in the Readme:
i_pool/1: 
![1](https://user-images.githubusercontent.com/32239569/119698499-95d00b00-be51-11eb-8ee5-38b3494f0811.png)
i_pool/6:
![6](https://user-images.githubusercontent.com/32239569/119698546-9ff20980-be51-11eb-902e-48288d1d4385.png)

You should get the following detections:
![sp_matches](https://user-images.githubusercontent.com/32239569/119698616-b26c4300-be51-11eb-96b9-b3574f5f96c7.png)

**Comment by Arka161** [comment]
Thank you for your results and help. I did some digging, and I think I know how why the black areas are coming. Your graphing code was as follows:

```
matched_img = cv2.drawMatches(img1_orig, kp1, img2_orig, kp2, matches,
                                      None, matchColor=(0, 255, 0),
                                      singlePointColor=(0, 0, 255))
```
The matches from the pre-processed images are placed on the original image with an offset I think. The original images have a size difference. Did you modify this line to avoid the random generation? 

Or did you run the code as is with my images and mention Width as 640 and Height as 480?

**Comment by rpautrat** [comment]
The img1_orig and img2_orig are actually already the resized images, so they are not really "original". Thus, the detected keypoints should exactly correspond to img_orig, without any offset.

I used the default parameter to run it, so not mentioning W and H. But by default they are already at 640 and 480.
