### ISSUE TITLE
Descriptors evaluation on COCO: sp_v6 get much lower accuracy that SIFT 

### ISSUE THREAD

**Issue by jonbakerfish** [rpautrat/SuperPoint#216]
Hi, I tried the homography estimation on COCO patches with all kinds of changes. The sp_v6 got only around 0.3957, while SIFT got 0.9450. All the config files are using the default parameters. Could you shed some light on these weird results?

**Comment by rpautrat** [comment]
Hi, indeed I get similar results as you for this experience.

I think that the main reason is that the COCO patches have rotations in [-90,90] degrees, while HPatches has very few rotations. Now even though sp_v6 has been trained with the same amount of rotation, it still struggles a bit for rotations larger than 45 degrees. This is mainly due to the fact that the architecture of SuperPoint is not made to handle rotations and can only learn the invariance through data augmentation. Given the uniform sampling used in the COCO patches generations, half of the images have a rotation larger than 45 degrees, so in half of the cases, SuperPoint probably gets a worse performance than SIFT, which performs very well with rotations.

You could try to run the same experiment with smaller rotations in COCO patches to verify this.

Another interesting experiment would be to add photometric augmentation to the COCO patches dataset. The robustness of SuperPoint to that should be higher than for SIFT, as it has specifically been trained for that. Thus the drop of performance compared to your previous numbers should be bigger for SIFT.
