### ISSUE TITLE
How to produce descriptors for images?

### ISSUE THREAD

**Issue by billyzju** [rpautrat/SuperPoint#22]
Hi, thank you for sharing this repo. 
I have trained a superpoint model based on your repo, and I can produce key points by using the model, the command I used is "python export_detections.py configs/super-point_coco_export.yaml superpoint_coco --pred_only --batch_size=5 --export_name=super-point-export". The key points produced by the trained model looks reasonable, but I failed to produce descriptors for input images.
Could you please provide some hints on this? Thank you very much!

**Comment by rpautrat** [comment]
Hi,
So if I understood well, you trained the superpoint model, not just the magicpoint model, right? Did you use the default config or did you tune the parameters? Because the descriptor part is still not stable and reliable and I couldn't get very good results for the descriptors so far.
But in any case if you want to export the descriptors, you need to use the script `export_descriptors.py` in the following manner:
`python export_descriptors.py configs/super-point_coco_export.yaml superpoint_coco --export_name=super-point-export`

**Comment by billyzju** [comment]
@rpautrat Thanks a lot!
Yes, I trained the superpoint model. To train superpoint model, I used the superpoint_coco.yaml, to export  keypoints, I basically used the magic-point_coco_export.yaml, but I chaged the model name as 'super_point'. 
I believe I have produced some descriptors so far, but I am not sure if the descriptors are reasonable(reliable or not), therefore, I want to print the detector_loss and descriptor_loss for every batch, respectively, so that I can see if the descriptor_loss is going down. However, I searched your codes carefully, I found that I can only print your final loss (which is the sum of detector_loss, warped_detector_loss and descripor_loss), So, how can I print these three losses respectively?
Thank you again!

**Comment by rpautrat** [comment]
You can check out the branch `superpoint_v1`: it is an updated version of superpoint (with minor differences, but you may have to retrain everything because the structure of the network changed slightly). Here the detector and descriptor loss are monitored separately.
Alternatively, you can stay on the master branch and just add the two lines in super_point.py as in the following commit: https://github.com/rpautrat/SuperPoint/commit/1fd53fa462ff0549601460fef53e58d1c3171247 and just retrain once your superpoint model.

**Comment by billyzju** [comment]
@rpautrat 
OK, I'll try it. Many thanks~

**Comment by rpautrat** [comment]
You can also evaluate your descriptor using the notebook `notebooks/descriptors_evaluation_on_hptches.ipynb`. It is an evaluation similar to what the authors of the original article did.

**Comment by kebinC** [comment]
@rpautrat  hi, i also train the superpoint, and found that the descriptor after training is worse to match. Do you have any idea to train the descriptor ?

**Comment by rpautrat** [comment]
Hi @kebinC,
As stated above, the current state of the code gives an unstable training of the descriptor with poor performance. I am working on it during my free time (but I don't really have time these days), so for now don't expect to get a good descriptor with the current code. If I manage to get a decent descriptor, I will for sure update the repo and the ReadMe consequently.
Of course you are free to try test it and maybe find what should be improved. I advise you in that case to start from the branch superpoint_v1 which has more recent fixes for the descriptor.

**Comment by kebinC** [comment]
@rpautrat  ok, i wiil try it.

**Comment by billyzju** [comment]
> You can check out the branch `superpoint_v1`: it is an updated version of superpoint (with minor differences, but you may have to retrain everything because the structure of the network changed slightly). Here the detector and descriptor loss are monitored separately.
> Alternatively, you can stay on the master branch and just add the two lines in super_point.py as in the following commit: [1fd53fa](https://github.com/rpautrat/SuperPoint/commit/1fd53fa462ff0549601460fef53e58d1c3171247) and just retrain once your superpoint model.

@rpautrat Hi, Rémi, thank you for your reply. Actually, I found that the model files (super_point.py) of  master branch and `superpoint_v1` looks same with each other. Also, the two-line codes you said [https://github.com/rpautrat/SuperPoint/commit/1fd53fa462ff0549601460fef53e58d1c3171247](url) are already contained in super_point.py of master branch (the branch I am using),  which is to say, the detector and descriptor loss were monitored separately. 
What I need now is to print (or save) the three losses for every batch separately, so, how can I do it? Simply add the print codes and retrain the model? These losses are Tensor type.
Thank you!

**Comment by rpautrat** [comment]
Oh indeed, you are right, I thought the master and superpoint_v1 branches were more different than that.

To have access to the detector and descriptor loss, why don't you use Tensorboard to monitor the losses (that's the use of the two lines of the commit, to store the values of the losses and display them in Tensorboard)?

**Comment by FangGet** [comment]
try this:
1. modify superpoint.py in _loss function , change return value to loss, detector_loss and descriptor_loss,
2.modify base_model.py in _gpu_tower function, add tower_descriptors list and tower the returned detector and des value, then your can follow the usage of tower_loss, and print it's value in evaluate step.
@billyzju

**Comment by SelinaChe** [comment]
Hi @rpautrat , i used the command `python export_descriptors.py configs/super-point_coco_export.yaml superpoint_coco --export_name=super-point-export` to export descriptors (have trained on coco dataset). But throwing an exception error `“KeyError: 'descriptors'”` when the code is executed in `pred1 = net.predict(data1, keys=['prob_nms', 'descriptors'])`. 
I used the default config when training on coco, is there any problem? The size the trained model `model.ckpt-200000.data-00000-of-00001` is about 8641k.

**Comment by rpautrat** [comment]
Hi @SelinaChe, can you show the content of the config file `superpoint_coco_export.yaml` that you use?

Note that the current implementation of superpoint is not working properly (the descriptor part). I will soon release a corrected version of the descriptors.

**Comment by SelinaChe** [comment]
Thanks @rpautrat . My superpoint_coco_export.yaml is the same as configs/magic-point_coco_export.yaml you provided. Where do I need to change?
Since the descriptor part is not provided, `evaluations/descriptor_evaluation.py` can not be used now?  I see the data access `data['desc']` in it. If so, could you please tell me a method or an idea about how to add descriptors exporting on it? Thank you.

**Comment by rpautrat** [comment]
You should rather use the file `configs/superpoint_hpatches.yaml` to export the descriptors then (and modify the dataset if you don't want to use it on HPatches). The problem was that the model name was still 'magic_point' in the config file you used, whereas it should be 'super_point' to have access to the descriptors.

`evaluations/descriptor_evaluation.py` can be used right now and you can compare Superpoint with SIFT and ORB for example. But you should observe poor results of Superpoint right now (since it is still buggy). Again, a corrected version will be soon released.

**Comment by rpautrat** [comment]
@billyzju @kebinC @SelinaChe: I have updated the branch superpoint_v1 with some corrections on the descriptors part. Now the descriptors produce coherent results, beat SIFT on illumination changes but need a bit more tuning of the parameters to beat SIFT on viewpoint changes I think.

**Comment by kebinC** [comment]
> @billyzju @kebinC @SelinaChe: I have updated the branch superpoint_v1 with some corrections on the descriptors part. Now the descriptors produce coherent results, beat SIFT on illumination changes but need a bit more tuning of the parameters to beat SIFT on viewpoint changes I think.

Hi @rpautrat , recently i check your corrections on the descriptors part, and have some doubt, why you change the shape of coord_cells and warped_coord_cells?

    #coord_cells = tf.to_float(tf.reshape(coord_cells, [1, Hc, Wc, 1, 1, 2]))
    #warped_coord_cells = tf.reshape(warped_coord_cells, [batch_size, 1, 1, Hc, Wc, 2])
    coord_cells = tf.to_float(tf.reshape(coord_cells, [1, 1, 1, Hc, Wc, 2]))
    warped_coord_cells = tf.reshape(warped_coord_cells, [batch_size, Hc, Wc, 1, 1, 2])

**Comment by rpautrat** [comment]
Hi!
Because it was wrong before I think. I had exchanged the role of the warped cells and the original ones. You can try it on a simple case with a small matrix, and you will see that the new configuration should be the one that works (that's how I found this bug actually).

**Comment by kebinC** [comment]
> Hi!
> Because it was wrong before I think. I had exchanged the role of the warped cells and the original ones. You can try it on a simple case with a small matrix, and you will see that the new configuration should be the one that works (that's how I found this bug actually).
ok, i got it, thanks.

**Comment by rpautrat** [comment]
This is a weird behavior indeed. When you say that it stopped, what message in the terminal did you get exactly? Or did it just display the same thing as if it was finishing normally?

Regarding your other question, if you want to monitor the time for detecting the points and computing the descriptors, I guess that you need to insert in the code some tools to measure time, like the python package time.

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
when i directly run the code of training superpoint, I got a oom error and then i set batch_size=1 in the file of superpoint_coco.yaml. Then it starts training like PIcture01.computer01.1.  when it runs about 10000 times, and it stopped while the GPU1080 does not work like PIcture01.computer01.2. Then I use another computer2 with GPU1070, it runs 25000times and stopped like PIcture01.computer02.1, the computer2 also is dead. I have to restart the computer2 which has 32G memory and has a GTX1070. I can not get the model.ckpt in the folder of superpoint_coco. Could you please give me some advice? 
PIcture01.computer01.1
![1 17 01](https://user-images.githubusercontent.com/44012688/51297673-3204ce80-1a5c-11e9-928d-1ca08fdf2f3b.png)
PIcture01.computer01.2
![Uploading 1710102.png…]()
 PIcture01.computer02.1
![Uploading 1302764901.jpg…]()

**Comment by rpautrat** [comment]
Ok, so when you say that the program stops, it's actually the computer that froze and wasn't doing anything anymore.
With your computer configuration, you should be able to run superpoint though. It may be due to the fact that other programs were running on your computer at the same time and took the whole memory at a given point. Can you try to run a training of superpoint by making sure that there are no other jobs running at the same time (both on CPU and GPU)? Because for example in your pictures there were always other jobs running on the GPU as well.

**Comment by lidongjiangBJTU** [comment]
Thanks for your reply, and i will try.

**Comment by rpautrat** [comment]
It does indeed look like a memory leak, even though it is rare in Python. It never happened to me (and no one ever complained about this before you), so this is rather weird.

There are some tools to monitor the memory consumption of the program and check for memory leaks. You can try for example the muppy module of the Python library pympler (https://pythonhosted.org/Pympler/muppy.html) or try to use Valgrind for Python (which is a software designed for C/C++ normally and that checks for memory leaks) since it seems to be possible according to this: https://stackoverflow.com/questions/20112989/how-to-use-valgrind-with-python

**Comment by lidongjiangBJTU** [comment]
It's very kind of you.

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
I measured the time that is used for the magicpoint detecting an image is about 0.075s and  superpoint predicting one image is about 10s. It was so slowly. I want to know what is your program running time for predicting one picture. I am confused by what i trained model. Why is it so slowly...I am looking forward your reply...

**Comment by rpautrat** [comment]
When I run superpoint on a 480x640 image with a GPU, I have personally a prediction in 0.3s on average. What did you use for your prediction? Are you sure that you ran it on GPU?
