### ISSUE TITLE
Superpoint evaluation error

### ISSUE THREAD

**Issue by akshadshyam** [rpautrat/SuperPoint#239]
Tried to run the match_features_demo on the given HPatches images. Got this error

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node superpoint/pred_tower0/vgg/conv1_1/conv/Conv2D (defined at match_features_demo.py:115)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](superpoint/pred_tower0/vgg/conv1_1/conv/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, superpoint/vgg/conv1_1/conv/kernel/read)]]

**Comment by rpautrat** [comment]
Hi, This seems to be a problem related to CuDNN and maybe to a wrong compatibility of versions. Which versions of TF, Cuda and CuDNN are you using?

**Comment by akshadshyam** [comment]
Thanks for the quick reply. I followed the installation instructions from [here](https://github.com/rpautrat/SuperPoint/issues/173)
My current versions are:
TF-gpu - 1.12
Cuda : 9.2
Cudnn: 7.6.5

**Comment by rpautrat** [comment]
This looks good I think.

You should probably look at the warning logs as suggested in the error message. This might tell you more about the error.

Otherwise I can't do much more to help you. This setup works for most people. You could maybe try to uninstall and reinstall TF and Cuda, this sometimes solves these kind of issues.
