### ISSUE TITLE
Do you have plan to improve hpatches-v?

### ISSUE THREAD

**Issue by litingsjj** [rpautrat/SuperPoint#241]
Sorry to bother you. this is a great project! I have a question about hpatches-v result. do you have any plan or advices to improve hpatches-v result for superpoint?

**Comment by rpautrat** [comment]
Hi, I am not currently working on the improvement of SuperPoint. But since the publication of SuperPoint, there have been multiple works that improved the performance of the detector and descriptor. For example for points, you could check [KeyNet](https://arxiv.org/pdf/1904.00889.pdf) and [DISK](https://arxiv.org/pdf/2006.13566.pdf).

**Comment by litingsjj** [comment]
Thanks a lot! I compared some images with superpoint and sift. For scale change, sift is much better than superpoint(or other cnn methods). the result is so terrible if the object in image1 is four times than in image2. I will read KeyNet and DISK that you provided. Also for descriptor matches, did you have some advices to improve? There are some paper used transformer, like superglue, LoFTR to get a better result, but the speed is so slow. I will so appreciate if you can solve my confusion, even if provide some clues. Thanks again!

**Comment by litingsjj** [comment]
thanks for your reply!
