### ISSUE TITLE
Index range in sample homography function

### ISSUE THREAD

**Issue by toru34** [rpautrat/SuperPoint#263]
On sampling scale value from a list `scales` in [sample_homography function](https://github.com/rpautrat/SuperPoint/blob/313a0a115961bc2a98a5ed1d7bde33fa99542398/superpoint/models/homographies.py#L117)、you initialise valid indices as `valid = tf.range(n_scales)` with a comment saying "all scales are valid except scale=1". But it seems this ignores the last element of `scales`, which is `scale ≠ 1`. not `scale = 1`.

I think this has to be `valid = tf.range(n_scales) +1`. Am I wrong?

**Comment by toru34** [comment]
Same for `tf.range(n_angles)`.

**Comment by rpautrat** [comment]
Hi, I think that you are correct.

I remember switching the 0 in the angle to the beginning of 'angles' a while ago to fix a bug (https://github.com/rpautrat/SuperPoint/commit/9807ef745a6e2a62ac989c49de2e68a6d6088354), but I can't remember why. But the fix is leaving it at the beginning anyway, so it should still be fine.
