### ISSUE TITLE
keypoints and descriptors

### ISSUE THREAD

**Issue by johnren-code** [rpautrat/SuperPoint#285]
Hi, I would like to know if the extracted feature points and descriptors can be matched with SuperGlue.

For example, after I get the feature points and descriptors using the function "extract_superpoint_keypoints_and_descriptors" in match_features_demo.py and give them to SuperGlue for processing, is this feasible? Is the format of the feature points and descriptors we get the same as the input format SuperGlue expects?

**Comment by rpautrat** [comment]
Hi, no SuperGlue has been trained and is expecting the original SuperPoint keypoints and descriptors: [https://github.com/magicleap/SuperPointPretrainedNetwork](https://github.com/magicleap/SuperPointPretrainedNetwork). You should use the pretrained weights of that repo with SuperGlue, otherwise the descriptors will be too different.

**Comment by johnren-code** [comment]
Sorry, I didn't fully understand you (My English is so poor). As you suggested, I plan to use the feature points and descriptors obtained from the trained SuperPoint to match using the magic leap team's SuperGlue pre-trained weights, is it right?

**Comment by rpautrat** [comment]
Yes, but you should not use the SuperPoint weights from this repo, but you should instead use the weights from the original SuperPoint (given in the link I provided above).

**Comment by johnren-code** [comment]
OK, Thank you very much!

**Comment by rpautrat** [comment]
You are welcome!
