### ISSUE TITLE
About match_features_deomo.py

### ISSUE THREAD

**Issue by johnren-code** [rpautrat/SuperPoint#286]
Hello! I'm sorry to bother you.

In match_features_demo.py, you use cv2.findHomography to get inliers. Here is the code:
`H, inliers = cv2.findHomography(matched_pts1[:, [1, 0]],matched_pts2[:, [1, 0]],cv2.RANSAC)`

I notice you use `matched_pts1[:, [1, 0]]` to invert the coordinates of the point, instead of using `matched_pts1` directly. I wonder why this step is needed. What's more, in the initial array `matched_pts1`, like [[1,2],[3,4],[5,6]], the first number of each two-dimensional coordinate represents the pixel coordinate in the width direction or the height direction of the image, like 1 in [1,2].

I want to use `cv2.findEssentialMat` to get essential matrix, should I do the same step like `cv2.findHomography`(convert `matched_pts1` to `matched_pts1[:, [1, 0]])`?

Looking forward to your reply!

**Comment by rpautrat** [comment]
Hi, thank you for your questions!

I think the inversion of the coordinates was a bug, which I have fixed now. Looking at the code, `matched_pts1` is indeed already in convention xy (i.e. the first coordinate is along the width and second along the height), which is what is expected by `cv2.findHomography`. So the inversion `[:, [1, 0]]` is indeed not necessary. Thank you for noticing it!

Note that the previous version was actually working correctly, because the homography was only used to remove outliers, and this goal was also achieved with the wrongly inverted coordinates. However, the predicted homography was wrong (but it was unused).

If you want to use `cv2.findEssentialMat`, you should also use the coordinates in xy convention (`matched_pts1` instead of `matched_pts1[:, [1, 0]]`).

**Comment by johnren-code** [comment]
Thank you very much！

**Comment by RemaDaher** [comment]
Hello there,

I would like to also ask about a similar thing that is done in [superpoint/evaluations/descriptor_evaluation.py]
```
    H, inliers = cv2.findHomography(m_keypoints[:, [1, 0]],
                                    m_warped_keypoints[:, [1, 0]],
                                    cv2.RANSAC)
```
Here the coordinates were also inverted. Is this also incorrect and needs to be changed or in this case it is necessary to flip the coordinates?

**Comment by rpautrat** [comment]
Hi, if I am not mistaken, the convention of `m_keypoints` and `m_warped_keypoints` is the opposite of the one expected in `cv2.findHomography`, so the flipping should be necessary here.
