### ISSUE TITLE
Problem about the resize operation

### ISSUE THREAD

**Issue by cxmscb** [rpautrat/SuperPoint#293]
Hi，rpautrat, sorry to disturb you. I wonder whether the the resize operation in the testing is the same as that of training. It seems that in the testing code `match_features_demo`, the resize operation does not preserve the ratio. But the resize operation in the training preserve the ratio.

**Comment by rpautrat** [comment]
Hi, it does not matter that much, because the network is fully convolutional and generalizes to new dimensions. We need a specific size during training to be able to batch images, but for testing, resizing is enough. We cannot crop at test time, because we would not detect any keypoint in the cropped areas.
