### ISSUE TITLE
Number of training images

### ISSUE THREAD

**Issue by rakooooon** [rpautrat/SuperPoint#42]
Hi , i wonder how many images you use when you train Magicpoint with the Synthetic images and MS COCO. images

Following the config file (magic-point_shapes.yaml), 'train_iter' is 200,000 and 'batch_size' is 64. 
Then did you use 12,800,000 synthetic images? or 12,800,000*NUM_GPUs?(How many Gpus you use?)

In 'magic-point_coco_export.yaml', 'train_iter' is 18000 and 'batch_size' is 32.
Then Number of total images is 576,000. Number of 'COCO 2014 train' images is 82,783. 576,000 can't divide by 82,783. 

And Is the config file of the pretrained model the same as the uploaded file in Github?

**Comment by rpautrat** [comment]
Hi!

At each iteration, batch_size x num_gpus images are used. So if you go until the end of the 200,000 iterations, you will indeed train on 12,800,000 x num_gpus images.

But in practice I stopped the training before it reached 'train_iter' iterations. For the training on synthetic images, I used for example around 40,000 iterations (with one GPU, so in total 2,560,000 images) and around 20,000 iterations when training MagicPoint on MS COCO (hence 1,280,000 images, that is 15 epochs over the training set of MS COCO).

Once the training has seen the 82,783 images of the training set of MS COCO, it starts again from the beginning of the dataset.

I think that the config file on Git changed compared to the one of the pretrained model. Even the code itself changed from the old pretrained model actually (and the new pretrained model does not work anymore, I am currently investigating why and that is why I removed the pretrained model from the current master branch).

**Comment by rakooooon** [comment]
Thanks for your reply.

If you do 20,000 iterations when training MagicPoint on MS COCO, then model is not trained full dataset in final epoch. Isn't it important to train full dataset?

In your case, what's the best model that is trained on synthetic images?
There is some options. Apply noise or not (photometric option in config). Apply homographic option or not.

**Comment by rpautrat** [comment]
Don't forget the batch size: 20,000 iterations times the batch size (64) means that you will actually see 1,280,000 images (a bit more than 15 times the whole MS COCO dataset). It doesn't really matter if you don't see all the images in the last epoch, since you have already seen them in the previous epochs. But if you prefer, you can perfectly change the 'train_iter' parameter to train on the full dataset even for the last epoch.

To get the best model, use both the photometric and homographic augmentations (as it is currently in https://github.com/rpautrat/SuperPoint/blob/master/superpoint/configs/magic-point_shapes.yaml).

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
Hi, before I saw this, I was a bit confused why it took so long to run each step. For example, the second step, running for about 7 hours. I now know that it is not necessary to iterate 200000 times.
I just started running the code for deep learning. The first one is your code. I saw this sentence "the new pretrained model does not work anymore" what does this mean? It means that the model that is training now cannot be used? What else does this code need to pay attention to? When I follow the steps, can I finally get a description and feature point for a picture? Forgive my question so shallow.

**Comment by rpautrat** [comment]
When I was speaking of "the new pretrained model", I meant that I had exported in a file the graph and the weights of the model that I trained, so that anybody could use it without any training. However I got some problems with this export and when I load the graph and the pretrained weights, it doesn't seem to work.
But if you train the network yourself by following the steps of the ReadMe, it works perfectly fine and you will get a good feature points detector and descriptor.

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
Thank you for your reply, I want to know how many times do you train when you train SuperPoint on MS-COCO? Is it 1700000 in the superpoint_coco.yaml configuration file? When I train according to the configuration file, to 70,000 times, the program Will be killed, because the LINUX kernel Out-Of-Memory killer mechanism. I am wondering if I can run less than 70,000 times. So I want to confirm the number of times you run, I can use as a reference.

**Comment by lidongjiangBJTU** [comment]
Thank you for your reply, I want to know how many times do you train when you train SuperPoint on MS-COCO? Is it 170000 in the superpoint_coco.yaml configuration file? When I train according to the configuration file, to 70,000 times, the program Will be killed, because the LINUX kernel Out-Of-Memory killer mechanism. I am wondering if I can run less than 70,000 times. So I want to confirm the number of times you run, I can use as a reference.

**Comment by rpautrat** [comment]
For SuperPoint, I actually used 170 000 iterations, as it is currently `superpoint_coco.yaml`.

To avoid the OOM, you can reduce the batch size and/or reduce the resolution of the images.

**Comment by lidongjiangBJTU** [comment]
Thank you very much for your quick reply, I know. I changed both batch size and eval_batch_size to 1, and I am training.

**Comment by rpautrat** [comment]
Good luck with the training! I hope that your memory will be enough :)

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
Hi, I ran export_descriptors.py, and I measured the time it took to process a picture. Do you see this normal? about 0.6s
![123](https://user-images.githubusercontent.com/44012688/54279126-38807400-45cf-11e9-8598-8d3b44c6136c.png)

**Comment by rpautrat** [comment]
Yes, I have about the same timings. Note that in `export_descriptors.py` there are actually two predictions, so the computation of the descriptors for a single image is done in about 0.3s.

**Comment by lidongjiangBJTU** [comment]
Thank you very much for your work and reply.

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
It takes 0.3s to process a picture, and the time is a bit long. I want to speed up the operation. The first thing I want to do is to convert the trained tensorflow model to the caffe framework. But I found the setting in the function below as write_meta_graph =False; I want to ask you, if I change this place to write_meta_graph=True and then output the model, will this generate a normal model? Because I noticed what you said, you encountered some problems when outputting the graph. The second question is that  what other lightweight can I do to improve the speed?
![image](https://user-images.githubusercontent.com/44012688/54860531-5b8cef80-4d56-11e9-812a-1fba754fc502.png)

**Comment by lidongjiangBJTU** [comment]
@rpautrat 
Hi, will you encounter this problem when you restore the model?
![image](https://user-images.githubusercontent.com/44012688/54879491-6e95e180-4e74-11e9-866e-0e69dd2c9093.png)

**Comment by zpfriedel** [comment]
So if I understand this right, when training MagicPoint on the synthetic images it is essentially one giant epoch since we continuously generate new images and never look at the same image twice. Is this correct?

**Comment by rpautrat** [comment]
Yes, that's correct.
