### ISSUE TITLE
retrian issue

### ISSUE THREAD

**Issue by LIANGXINKAI** [rpautrat/SuperPoint#46]
Thanks for u fantastic code.
There are somethings trouble me，this code never use the trained model from COCO or synthetic dataset，can u share the reason?
NEXT problem is why we can not use the offical superpoint trained model to train our own model，can u share this code and experience

**Comment by rpautrat** [comment]
Hi,
Yes, the training of MagicPoint on the synthetic dataset or COCO is only used here to generate reliable feature points ground truth. It would be possible indeed to pretrain the detector part with those previous weights and fine-tune with the full architecture (detector + descriptor), but I didn't try in practice. Training from scratch already gave similar results as in the original paper.

About the next problem, what do you call "the offical superpoint trained model"? Do you mean the one from MagicLeap (one such model is available here: https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork)? Otherwise this repo explains how to train your own model in Tensorflow.

**Comment by LIANGXINKAI** [comment]
thanks for u reply.
I means how to retrain our own model in your code(this one) from our own dataset  by the model(one such model is available here: https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork)?
I think once I can retrain the model from the one, THE result is more robust in my own dataset.
I really appreciate your work.

**Comment by rpautrat** [comment]
I guess it is a bit late to answer this, but you need to create a file similar to `superpoint/datasets/coco.py` that load and preprocess your own dataset. You can then use this file by specifying the parameter data->name of your config file and putting there the name of your own dataset.
