### ISSUE TITLE
errors about the Hpatches dataset groundtruth homography H_ref_1

### ISSUE THREAD

**Issue by amandalqy** [rpautrat/SuperPoint#62]
Hello,I have met a problem when I try to map the feature points of the reference image to the warped image using the ground truth  homography H_ref_X. I find that it will project to wrong feature points using the ground truth  homography H_ref_X. For example，when I try to project the green point in the laptop of the first picture, the corresponding feature point (red) finded in the second picture using H_ref_X is not correct Obviously, the second point is even out of the image's boundary. Can you help me solve this problem? Thanks a lot.
![image3](https://user-images.githubusercontent.com/44419296/56073497-8a3b3a80-5dd7-11e9-8a3d-dc2c077aeb92.png)
![image4](https://user-images.githubusercontent.com/44419296/56073499-8f988500-5dd7-11e9-9d42-861fcdd08cd4.png)

**Comment by rpautrat** [comment]
Hi! What exactly did you use to warp the points? Because it might be that you used the inverse of the homography that you wanted to use (which happens very often when working with homographies). If I remember correctly, the H_ref_i means that if you have a point X_ref in ref image, then the corresponding warped point will be X_i = H_ref_i * X_ref. But with some tools that warp images (such as OpenCV's warpAffine), it's the inverse of H_ref_i that would be used.

So please double-check that you are using the correct homography (maybe try to do the same warp by inverting H_ref_i in your case and see if you get the correct result).

Btw, if you want to you use HPatches with this repo, I recommend you to use the 1.3 Gb version of HPatches (http://icvl.ee.ic.ac.uk/vbalnt/hpatches/hpatches-sequences-release.tar.gz), where the homographies will be named differently (H_1_X instead of H_ref_X).

**Comment by amandalqy** [comment]
Thanks very much. I would try again.

**Comment by rpautrat** [comment]
Did you solve your problem?

**Comment by amandalqy** [comment]
@rpautrat ,I have solved the problem,thanks a lot. I haven't been on github recently, so I just saw the message.

**Comment by rpautrat** [comment]
Great, good to know!
