### ISSUE TITLE
'homography is not a file in the archive'

### ISSUE THREAD

**Issue by l1346792580123** [rpautrat/SuperPoint#63]
When I head over to descriptors_evaluation_on_hpatches.ipynb to proceed to the evaluation.  I get an error
![20190415094203](https://user-images.githubusercontent.com/25956606/56103013-0f068f80-5f63-11e9-84c7-d8da590fb8ea.png)
The experiment name is superpoint_hpatches-v just generated as the step 7 in README, but I only generate 10 .npz files. Does it matter?

**Comment by rpautrat** [comment]
How did you stop the generation of .npz files at 10 exactly? By killing the process with a Ctrl C or by setting the parameter 'eval_iter' to 10?

Because it could be that when you stopped the program `export_descriptors.py`, the last npz was only partially created and the 'homography' parameter has not yet been added to the archive. You can check that by deleting the last npz created and see if you still have the error.

**Comment by l1346792580123** [comment]
Yes, I kill the process with Ctrl C. And now I delete the last npz file and it works well. Thanks for your quick reply
