### ISSUE TITLE
Issue for evaluating descriptor.

### ISSUE THREAD

**Issue by QianshengGu** [rpautrat/SuperPoint#72]
@rpautrat Hi, I'm confused about the evaluation of the descriptor. In the scripts https://github.com/rpautrat/SuperPoint/blob/master/superpoint/evaluations/descriptor_evaluation.py, you evaluate the correctness of the estimated homography, which is not reported in your paper. and I can not find the code to evaluate the M.score and NN mAP of descriptor? Can you give me some advice? Thanks a lot.

**Comment by rpautrat** [comment]
Hi,
It's not my paper, the original paper is from the team of Magic Leap (Daniel DeTone et al.). I just implemented their paper as closely as I could.
The correctness of the homography estimation that I evaluate is in the paper (in table 4). I didn't implement the matching score and NN mAP of the descriptor, that's why you can't find it.

**Comment by QianshengGu** [comment]
@rpautrat Thank you very much for your reply, as well as your remarkable work.
