### ISSUE TITLE
Speed up for 4k or even 8k images

### ISSUE THREAD

**Issue by kimjongyoung** [rpautrat/SuperPoint#85]
When we use images of 4k resolution as input, the inference speed slows down to 0.7-1fps.
I want your opinion, would it be possible to have speed improvement by converting FP32 CNNs into INT8?

Thanks in advance.

**Comment by rpautrat** [comment]
The size of the network would certainly be smaller with integers, but I don't know if it would be really faster.

If you really want a faster inference, I would recommend you to replace the VGG encoder by a lighter network, like a MobileNet (https://arxiv.org/abs/1704.04861).

**Comment by j-lag** [comment]
Hi there!
I got around 2fps for a 640x480 image on a Geforce 1080 Ti and tensorflow 1.12.0.
Is this normal? The original paper advertise a speed of 70fps.
Regards

**Comment by rpautrat** [comment]
Hi!

Yes, I roughly have the same speed on such images.

The authors of the paper used a Pytorch implementation (which is slightly faster than Tensorflow on average I think) and they are using in practice a bilinear interpolation at the end of the descriptor head (or at least their public implementation is using it), instead of a bi-cubic interpolation like here or as described in the paper (which is slower). This probably doesn't explain the huge difference observed in speed, so this implementation is probably not as optimized as their own version.

**Comment by jadehh** [comment]
Hi~
I got 20fps for a 640x480 image on a RTX 2080 Ti and tensorflow 1.10.0.


> Hi!
> 
> Yes, I roughly have the same speed on such images.
> 
> The authors of the paper used a Pytorch implementation (which is slightly faster than Tensorflow on average I think) and they are using in practice a bilinear interpolation at the end of the descriptor head (or at least their public implementation is using it), instead of a bi-cubic interpolation like here or as described in the paper (which is slower). Note also that the NMS operation applied at the end is probably not included in the count of the 70 FPS of the original paper. All of this probably doesn't explain the huge difference observed in speed, so this implementation is probably not as optimized as their own version.
